name: google-server-api
version: "0.4.1.0"
category: "Web"
synopsis: "Google APIs for server to server applications"
description:
  This library provides a way to use Google API for server to server applications.
license: "MIT"
author: "Kadzuya Okamoto"
copyright: "2018 Kadzuya Okamoto"
maintainer: "arow.okamoto+github@gmail.com"

extra-source-files:
  - README.md

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.14 && < 5
  - HsOpenSSL
  - RSA
  - aeson
  - aeson-casing
  - base64-bytestring
  - bytestring
  - http-api-data
  - http-client
  - http-client-tls
  - http-media
  - mime-mail
  - monad-control
  - monad-logger
  - mtl
  - servant
  - servant-client
  - text
  - time
  - transformers
  - transformers-base
  - unix-time
  - unordered-containers
  - wai
  - wai-extra
  - warp

library:
  source-dirs:
    - src
  exposed-modules:
    - Google.Client
    - Google.Form
    - Google.JWT
    - Google.Response
    - Google.Type

github: arowM/haskell-google-server-api
